### ISSUE TITLE
Failed to run the script

### ISSUE THREAD

**Issue by AntonBelousov** [IIIImmmyyy/frida-il2cppDumper#10]
Please, help me understand, what's going wrong?

I run 
`frida -f com.bytetyper.iwantpizza -l _agent.js -D 9c2648e95b631f0715e504b14e5127077cad60df --no-pause`

And get 
```
    ____
    / _  |   Frida 15.1.17 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to iPhone (id=9c2648e95b631f0715e504b14e5127077cad60df)
Spawned `com.bytetyper.iwantpizza`. Resuming main thread!               
Error: failed to open file (No such file or directory)
    at <anonymous> (agent/dumper.js:9)
    at call (native)
    at o (node_modules/browser-pack/_prelude.js:1)
    at <anonymous> (node_modules/browser-pack/_prelude.js:1)
    at <anonymous> (agent/index.ts:2)
    at call (native)
    at <anonymous> (/_agent.js:1119)
    at call (native)
    at <anonymous> (/_agent.js:1119)
    at call (native)
    at o (node_modules/browser-pack/_prelude.js:1)
    at r (node_modules/browser-pack/_prelude.js:1)
    at <eval> (/_agent.js:1395)
[iPhone::com.bytetyper.iwantpizza ]->
```

**Comment by IIIImmmyyy** [comment]
sorry， it's not support IOS, it's need file dump the info, this path is not support IOS, you can edit the path to IOS support




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IIIImmmyyy/frida-il2cppDumper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月13日(星期天) 晚上7:07
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[IIIImmmyyy/frida-il2cppDumper] Failed to run the script (Issue #10)





 
Please, help me understand, what's going wrong?
 
I run
 frida -f com.bytetyper.iwantpizza -l _agent.js -D 9c2648e95b631f0715e504b14e5127077cad60df --no-pause
 
And get
     ____     / _  |   Frida 15.1.17 - A world-class dynamic instrumentation toolkit    | (_| |     &gt; _  |   Commands:    /_/ |_|       help      -&gt; Displays the help system    . . . .       object?   -&gt; Display information about 'object'    . . . .       exit/quit -&gt; Exit    . . . .    . . . .   More info at https://frida.re/docs/home/    . . . .    . . . .   Connected to iPhone (id=9c2648e95b631f0715e504b14e5127077cad60df) Spawned `com.bytetyper.iwantpizza`. Resuming main thread!                Error: failed to open file (No such file or directory)     at <anonymous&gt; (agent/dumper.js:9)     at call (native)     at o (node_modules/browser-pack/_prelude.js:1)     at <anonymous&gt; (node_modules/browser-pack/_prelude.js:1)     at <anonymous&gt; (agent/index.ts:2)     at call (native)     at <anonymous&gt; (/_agent.js:1119)     at call (native)     at <anonymous&gt; (/_agent.js:1119)     at call (native)     at o (node_modules/browser-pack/_prelude.js:1)     at r (node_modules/browser-pack/_prelude.js:1)     at <eval&gt; (/_agent.js:1395) [iPhone::com.bytetyper.iwantpizza ]-&gt;  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by intelligentpotato** [comment]
Same on Android. The compiled _agent.js from the repository works, except for various memory-related errors with Unity 2021.

```
$ frida -U -f com.X -l _agent.js
     ____
    / _  |   Frida 16.0.2 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to Pixel 2 XL (id=X)
Spawned `com.X`. Resuming main thread!
Error: No such file or directory
    at <anonymous> (agent/dumper.js:9)
    at call (native)
    at o (node_modules/browser-pack/_prelude.js:1)
    at <anonymous> (node_modules/browser-pack/_prelude.js:1)
    at <anonymous> (agent/index.ts:2)
    at call (native)
    at <anonymous> (/root/frida-il2cppDumper/_agent.js:866)
    at call (native)
    at <anonymous> (/root/frida-il2cppDumper/_agent.js:866)
    at call (native)
    at o (node_modules/browser-pack/_prelude.js:1)
    at r (node_modules/browser-pack/_prelude.js:1)
    at <eval> (/root/frida-il2cppDumper/_agent.js:1013)
    at evaluate (native)
    at <anonymous> (/frida/repl-2.js:1)
```
```
$ git clone https://github.com/IIIImmmyyy/frida-il2cppDumper.git
$ cd frida-il2cppDumper
$ rm _agent.js
$ npm install
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

> frida-agent-example@1.0.0 prepare
> npm run build


> frida-agent-example@1.0.0 build
> frida-compile agent/index.ts -o _agent.js -c


added 257 packages, and audited 258 packages in 10s

43 packages are looking for funding
  run `npm fund` for details

4 vulnerabilities (3 high, 1 critical)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
$ npm run build

> frida-agent-example@1.0.0 build
> frida-compile agent/index.ts -o _agent.js -c

```
```
node --version
v16.18.1
npm --version
8.19.2
frida-compile --version
16.0.2
```
