### ISSUE TITLE
大佬 dump 失败 ，样本 https://lachs.lanzoue.com/iFqih0g5rnhe

### ISSUE THREAD

**Issue by iyzwei4666** [IIIImmmyyy/frida-il2cppDumper#13]
<img width="796" alt="image" src="https://user-images.githubusercontent.com/19775371/202458834-ea66a04e-5c40-4b29-ac74-7733cece8862.png">

**Comment by IIIImmmyyy** [comment]
已解决

**Comment by IIIImmmyyy** [comment]
使用新_agent.js
