### ISSUE TITLE
ios如何dump

### ISSUE THREAD

**Issue by LarissaLycoris** [IIIImmmyyy/frida-il2cppDumper#15]
把提取的so（dylib）放在js同一个目录吗

**Comment by IIIImmmyyy** [comment]
使用frida 和安卓一样的命令 查询IOS的运行包名 使用frida-ps -Uai

**Comment by LarissaLycoris** [comment]
> 使用frida 和安卓一样的命令 查询IOS的运行包名 使用frida-ps -Uai

frida-server 安卓有版本，ios没版本 ios要使用哪个呢？安卓我已经成功运行dump 但是游戏有检测 会闪退，现在打算去弄ios看看
