### ISSUE TITLE
dump失败

### ISSUE THREAD

**Issue by PackageInstaller** [IIIImmmyyy/frida-il2cppDumper#16]
![image](https://github.com/user-attachments/assets/13730209-67cf-4146-9f5c-a43c0e92c0d0)
![image](https://github.com/user-attachments/assets/83019349-70e9-44ec-b39a-e147671c62f6)

执行指令是`frida -U -f jp.boi.mementomori.android -l frida-il2cppDumper/_agent.js`

游戏是mementomori，可以在google商店(qooapp也可)下载到，安装包800M+我就不放了，大佬帮忙康康

**Comment by IIIImmmyyy** [comment]
可以了 使用最新代码即可

**Comment by PackageInstaller** [comment]
感谢，可以了🙏
