### ISSUE TITLE
TypeError: il2cpp_image_get_class is not a function

### ISSUE THREAD

**Issue by ttxnz** [IIIImmmyyy/frida-il2cppDumper#2]
使用的frida 12.10.0版本
并且也用frida-compile编译了，--runtime=v8 也加了，但提示TypeError: il2cpp_image_get_class is not a function
![1L}H0 8GH69TZ5E AYTL H](https://user-images.githubusercontent.com/50402456/146918597-2edf0e68-4b36-4106-b0d6-2c222bc704d9.png)

不知道是什么问题，佬能给个解决办法吗

**Comment by IIIImmmyyy** [comment]
大概率是Unity版本的问题  查询以下该游戏的引擎版本 我将为其兼容

 解压APK ->assets->bin->data 随意右键使用记事本打开一个资源文件
![QQ图片20211222102439](https://user-images.githubusercontent.com/14196832/147024462-cab78d6e-abe3-4cb9-96af-35f5077f2cb6.png)
图示即为unity版本

**Comment by ttxnz** [comment]
Unity版本是2017.4.39f1

**Comment by IIIImmmyyy** [comment]
> Unity版本是2017.4.39f1

方便告知是什么游戏吗？

**Comment by IIIImmmyyy** [comment]
> Unity版本是2017.4.39f1

已找到原因 引擎版本为2017.4系列时 由于get_class缺失  需要手动找FromTypeDefinition 来进行主动调用 稍后将同步如何寻找该函数教程

**Comment by ttxnz** [comment]
游戏是明日方舟 https://ak.hypergryph.com/
感谢大佬出教程( ˃̶̤́ ꒳ ˂̶̤̀ )

**Comment by ttxnz** [comment]
大佬。。目前是找到了FromTypeDefinition，但在这之后还是错误了
![_BB}Q@BAR73YP`% V1YHXF9](https://user-images.githubusercontent.com/50402456/147258796-1e558787-d165-431e-95d8-f5290c0e87dc.png)
![NSU$} J Z~8H$@J5UWC}8LB](https://user-images.githubusercontent.com/50402456/147258924-f3adcf4d-9426-4554-9d6c-7a82b4bcae71.png)

**Comment by IIIImmmyyy** [comment]
> 大佬。。目前是找到了FromTypeDefinition，但在这之后还是错误了 ![_BB}Q@BAR73YP`% V1YHXF9](https://user-images.githubusercontent.com/50402456/147258796-1e558787-d165-431e-95d8-f5290c0e87dc.png) ![NSU$} J Z~8H$@J5UWC}8LB](https://user-images.githubusercontent.com/50402456/147258924-f3adcf4d-9426-4554-9d6c-7a82b4bcae71.png)

初步判断是TP保护检测到了frida 造成了dumper中断 由于过保护不在本范畴内 所以请自行过保护

**Comment by ttxnz** [comment]
好的，感谢大佬！
