### ISSUE TITLE
Have problems when execute the script

### ISSUE THREAD

**Issue by s5k** [IIIImmmyyy/frida-il2cppDumper#5]
Good day, IIIImmmyyy!
I have cloned a source from the repo and configured the package name and version, but when I push the code was built to the android emulator has some error. Please help me. Thank you in advance.

Specs:
Both Frida desktop and server 15.1.14.

My configuration:
```javascript
export var UnityVer = {
    V_2017_4_31f1: "2017.4.31f1",
    V_2018_4_36f1: "2018.4.36f1",
    V_5_6_4p4: "5.6.4p4"
};
export const soName = "libil2cpp.so";

export  const pkg_name="com.vng.codmvn";

export const UNITY_VER = UnityVer.V_5_6_4p4;
```

![alt text](https://i.imgur.com/P0V1a9R.png "bugs")

**Comment by CkYtxwz** [comment]
https://www.52pojie.cn/forum.php?mod=viewthread&tid=1559859

**Comment by IIIImmmyyy** [comment]
> Good day, IIIImmmyyy! I have cloned a source from the repo and configured the package name and version, but when I push the code was built to the android emulator has some error. Please help me. Thank you in advance.
> 
> Specs: Both Frida desktop and server 15.1.14.
> 
> My configuration:
> 
> ```js
> export var UnityVer = {
>     V_2017_4_31f1: "2017.4.31f1",
>     V_2018_4_36f1: "2018.4.36f1",
>     V_5_6_4p4: "5.6.4p4"
> };
> export const soName = "libil2cpp.so";
> 
> export  const pkg_name="com.vng.codmvn";
> 
> export const UNITY_VER = UnityVer.V_5_6_4p4;
> ```
> 
> ![alt text](https://camo.githubusercontent.com/b0be678a4d34f8ad935fc5175286e9c4f48cb80ff0c8a2b3ae8bb9513f402b68/68747470733a2f2f692e696d6775722e636f6d2f503056316139522e706e67)

it's not support android emulator  , please use phone
