### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by CkYtxwz** [IIIImmmyyy/frida-il2cppDumper#7]
I found that when the game has x86 library, it will succeed on Android simulator, but when it doesn't, it will report an error. Why?

**Comment by IIIImmmyyy** [comment]
can you provide this game ? I will check it.

**Comment by CkYtxwz** [comment]
I also checked it. When the x86 library is deleted, it will report typeerror: not a function

This is a link https://ckwhy.lanzouo.com/ihaD8zck68b

I'm not sure if you can use this link

**Comment by IIIImmmyyy** [comment]
![image](https://user-images.githubusercontent.com/14196832/151524688-d4a95dd3-1012-4ea8-a6e6-565c80d3fc58.png)
it's worked success in this game, but I don't use in simulator.  can you  use in  android devices?

**Comment by CkYtxwz** [comment]
I will try it with Android device. Thank you very much
