### ISSUE TITLE
报错 跑不动

### ISSUE THREAD

**Issue by qajknsdjaks** [IIIImmmyyy/frida-il2cppDumper#8]
(py38env) MacBookPro:agent Ken$ frida -U -f com.manling.xmqy.aligames --no-pause -l index.ts 
     ____
    / _  |   Frida 14.2.2 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://www.frida.re/docs/home/
Failed to load script: script(line 2): SyntaxError: expecting '('       

Thank you for using Frida!
(py38env) MacBookPro:agent Ken$

**Comment by IIIImmmyyy** [comment]
正确的文件应该为 _agent.js文件
