### ISSUE TITLE
怎么dump 字符串？

### ISSUE THREAD

**Issue by zbx911** [IIIImmmyyy/frida-il2cppDumper#9]
求解。

**Comment by IIIImmmyyy** [comment]
描述具体

**Comment by zbx911** [comment]
Il2CppDumper-v6.7.6 生成的 stringliteral.json ，是否可在你的工具中实现？

**Comment by IIIImmmyyy** [comment]
暂时不能，字符串的映射表目前没有公开api来调用，只能通过IDA手动分析来实现

**Comment by zbx911** [comment]
> 暂时不能，字符串的映射表目前没有公开api来调用，只能通过IDA手动分析来实现

那il2cpp怎么调用字符串的呢
